# 二元关系
## 二元关系的判定
需要下载numpy
``` shell
pip install numpy
```
numpy 官方手册
https://numpy.org/doc/stable/reference/index.html

在下文的示例中, 二元关系用矩阵A表示, $A[i][j] = 1 $ 代表存在二元关系 $(i, j)$,  $A[i][j] = 0 $ 代表不存在二元关系 $(i, j)$.

In [2]:
import numpy as np

def check_properties(matrix):
    n = len(matrix)
    
    # 自反性
    is_reflexive = np.all(np.diag(matrix) == 1)
    
    # 反自反性
    is_irreflexive = np.all(np.diag(matrix) == 0)
    
    # 对称性
    is_symmetric = np.all(matrix == matrix.T)
    
    # 反对称性
    is_antisymmetric = np.all((matrix == 0) | (matrix.T == 0) | (np.eye(n) == 1))
    
    # 传递性 思考一下为什么?
    is_transitive = np.all((matrix @ matrix) <= matrix)

    
    return {
        "自反性": is_reflexive,
        "反自反性": is_irreflexive,
        "对称性": is_symmetric,
        "反对称性": is_antisymmetric,
        "传递性": is_transitive
    }

# 示例矩阵
matrix = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])

# 检查属性
properties = check_properties(matrix)
for prop, value in properties.items():
    print(f"{prop}: {'是' if value else '否'}")

自反性: 是
反自反性: 否
对称性: 是
反对称性: 否
传递性: 否


## 计算二元关系闭包

In [7]:
def reflexive_closure(matrix):
    """计算自反闭包"""
    closure = matrix.copy()
    np.fill_diagonal(closure, 1)
    return closure

def symmetric_closure(matrix):
    """计算对称闭包"""
    closure = matrix.copy()
    closure = np.maximum(closure, closure.T)
    return closure

def transitive_closure(matrix):
    """计算传递闭包"""
    n = len(matrix)
    closure = matrix.copy()
    for _ in range(n):
        closure_new = np.minimum(closure @ closure, 1)
        if np.array_equal(closure, closure_new):
            break
        closure = closure_new
    return closure

matrix = np.array([
    [1, 1, 0],
    [0, 1, 0],
    [1, 0, 0]
])

reflexive_closure_matrix = reflexive_closure(matrix)
symmetric_closure_matrix = symmetric_closure(matrix)
transitive_closure_matrix = transitive_closure(matrix)

print("自反闭包:")
print(reflexive_closure_matrix)
print("对称闭包:")
print(symmetric_closure_matrix)
print("传递闭包:")
print(transitive_closure_matrix)

自反闭包:
[[1 1 0]
 [0 1 0]
 [1 0 1]]
对称闭包:
[[1 1 1]
 [1 1 0]
 [1 0 0]]
传递闭包:
[[1 1 0]
 [0 1 0]
 [1 1 0]]
